{
  "format_version": 1,
  "sksl": {
    "entrypoint": "ripple_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform vec2 uTouchPoint;\nuniform float uProgress;\nuniform float uIntensity;\nuniform vec3 uColor;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = fragCoord / uResolution;\n    float aspect = uResolution.x / uResolution.y;\n    vec2 correctedUV = vec2(uv.x * aspect, uv.y);\n    vec2 correctedTouch = vec2(uTouchPoint.x * aspect, uTouchPoint.y);\n    float dist = distance(correctedUV, correctedTouch);\n    float waveRadius = uProgress * 1.60000002384185791015625;\n    float waveDist = dist - waveRadius;\n    float rings = sin((waveDist * 28.0) - ((uProgress * 3.1415927410125732421875) * 4.0));\n    rings = pow(abs(rings), 0.60000002384185791015625) * sign(rings);\n    rings = (rings * 0.5) + 0.5;\n    float bandWidth = 0.119999997317790985107421875 + (uProgress * 0.180000007152557373046875);\n    float bandMask = smoothstep(bandWidth, 0.0, abs(waveDist));\n    float distanceFade = 1.0 - smoothstep(0.0, 1.440000057220458984375, dist);\n    float progressFade = smoothstep(0.0, 0.1500000059604644775390625, uProgress) * smoothstep(1.0, 0.699999988079071044921875, uProgress);\n    float alpha = (((rings * bandMask) * distanceFade) * progressFade) * uIntensity;\n    float edgeHighlight = (((smoothstep(0.0199999995529651641845703125, 0.0, abs(waveDist)) * progressFade) * distanceFade) * uIntensity) * 0.4000000059604644775390625;\n    alpha += edgeHighlight;\n    alpha = clamp(alpha, 0.0, 1.0);\n    fragColor = vec4(uColor * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uTouchPoint",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uProgress",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uIntensity",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uColor",
        "rows": 3,
        "type": 10
      }
    ]
  }
}