{
  "format_version": 1,
  "sksl": {
    "entrypoint": "shimmer_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform float uAngle;\nuniform float uSpeed;\nuniform vec3 uColor;\nuniform float uWidth;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = fragCoord / uResolution;\n    vec2 dir = vec2(cos(uAngle), sin(uAngle));\n    float projection = dot(uv - vec2(0.5), dir) + 0.5;\n    float totalRange = 1.0 + (uWidth * 2.0);\n    float sweep = mod((uTime * uSpeed) * 0.4000000059604644775390625, totalRange) - uWidth;\n    float dist = projection - sweep;\n    float halfWidth = uWidth * 0.5;\n    float band = smoothstep(halfWidth, 0.0, abs(dist));\n    band *= band;\n    float halo = smoothstep(halfWidth * 3.0, 0.0, abs(dist)) * 0.1500000059604644775390625;\n    float shimmer = band + halo;\n    float edgeFade = ((smoothstep(0.0, 0.07999999821186065673828125, uv.x) * smoothstep(1.0, 0.920000016689300537109375, uv.x)) * smoothstep(0.0, 0.07999999821186065673828125, uv.y)) * smoothstep(1.0, 0.920000016689300537109375, uv.y);\n    shimmer *= edgeFade;\n    vec2 perpDir = vec2(-dir.y, dir.x);\n    float perpDist = abs(dot(uv - vec2(0.5), perpDir));\n    shimmer *= smoothstep(0.5, 0.0, perpDist);\n    shimmer = clamp(shimmer, 0.0, 1.0);\n    vec3 color = uColor * shimmer;\n    fragColor = vec4(color, shimmer);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uAngle",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uSpeed",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uWidth",
        "rows": 1,
        "type": 10
      }
    ]
  }
}